version: '3'

services:
  flask-api:
    image: isurufernando/flask-api:latest
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: isurufernando/mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: local-mysql
