version: '3.8'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: isurufernando/flask-api:latest
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db

  mysql-db:
    image: isurufernando/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GIT_PERF
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    expose:
      - "3306"
